name: build-pro-image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - app.js
      - config.js
      - package.json
      - fetchURLBy*.js
      - utils/**
      - .github/workflows/push_docker.yaml

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6,linux/s390x
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/migu_video:pro
            ghcr.io/${{ github.repository_owner }}/migu_video:latest
